### ISSUE TITLE
vtkFullScreenRenderWindow and gradient background 

### ISSUE THREAD

**Issue by R3d3y3s** [Kitware/vtk-js#887]
Hi,
is it possible to setup the vtkFullScreenRenderWindow's background to a linear gradient background (for instance with a css element or by setting some attributes) ?
```javascript
fullScreenRenderer = vtkFullScreenRenderWindow.newInstance({
            background: [1, 1, 1], 
            rootContainer: container,
            containerStyle: {
                height: '100%',
                width: '100%',
                position: 'absolute'
            },
        });
```
css element

```css
.backgroundGradient {
    background: linear-gradient(to bottom, #1300DD 0%, #DEDEDE 100%);
    height: '100%';
    width: '100%';
    position: 'absolute';
}
```
many thanks for your reply
